@startuml diagr
left to right direction

actor Участник

Участник --> (Оставить отзыв)
Участник --> (Просматривать информацию об авторах)
Участник --> (Просматривать каталог) 

actor Библиотекарь

Библиотекарь --> (Выдавать и принимать книги)
Библиотекарь --> (Отслеживать задолженности)
Библиотекарь --> (Работать с информацией об авторах и книгах)

@enduml