@startuml block
:Начало;
:Запрос на книгу/
if (Есть в наличии?) then (Нет)
    :Статус "Недоступна"]
else (Да)
    if (Имеется задолженность?) then (Да)
        :Отказ в брони]
    else (Нет)
        :Зафиксировать бронь]
        :Статус "Выдана"]
    endif
endif
:Конец;
@enduml
