@startuml 
:Начало;
:Ввод новой книги/
if (Имеется дефект?) then (Да)
    :Отказ]
else (Нет)
   :Присвоить ID]
   if (Есть автор в БД?) then (Нет)
    :Добавить]
   else (Да)
   endif
:Ввести краткую информацию о книге/ 
:Установить статус "Доступна"]
endif
:Конец;
@enduml