@startuml diagr
left to right direction

actor Участник

Участник -- (Оставить отзыв)
Участник -- (Просматривать информацию об авторах)
Участник -- (Просматривать каталог) 
Участник -- (Брать книги из библиотеки)

actor Библиотекарь

Библиотекарь -- (Выдавать и принимать книги)
Библиотекарь -- (Отслеживать задолженности)
Библиотекарь -- (Управлять библиографической информацией) 
(Исправлять опечатки) ..> (Управлять библиографической информацией): <<include>> 
(Редактировать биографии авторов) ..> (Управлять библиографической информацией): <<include>> 
@enduml